name: "Update Wiki Data"

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "0 * * * */6"

jobs:
  update_wiki:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v7
      - name: "Install Python"
        uses: actions/setup-python@v7
        with:
          python-version: "3.x"
      - name: "Install requests"
        run: "pip install requests"
      - name: "Run Python Script"
        env:
          WIKI_URL: ${{ secrets.WIKI_URL }}
          API_URL: ${{ secrets.API_URL }}
          WIKI_USERNAME: ${{ secrets.WIKI_USERNAME }}
          WIKI_BOT_PASSWORD: ${{ secrets.WIKI_BOT_PASSWORD }}
        run: "python sync.py"
